#!/bin/sh
set -e

case "$1" in
  configure)
    if ! getent group android_everybody >/dev/null; then
      groupadd --gid 9997 android_everybody
    fi

    for gid in 2901 2902 2903 2904 2905 2906 2907 2908 2909; do
      group="android_oem_$gid"
      getent group "$group" >/dev/null || groupadd --gid "$gid" "$group"
    done

    usermod -aG android_everybody,android_oem_2901,android_oem_2902,android_oem_2903,android_oem_2904,android_oem_2905,android_oem_2906,android_oem_2907,android_oem_2908,android_oem_2909 droidian

    systemctl mask serial-getty@hvc0.service
    systemctl mask droidian-fpd
    ;;
  *)
    echo "Unknown argument: $1" >&2
    exit 1
    ;;
esac

exit 0
