# This is a basic workflow to help you get started with Actions

name: Build adaptation package for POCO F5/Redmi Note 12 Turbo

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "droidian" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    container: quay.io/droidian/build-essential:current-amd64

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: Update repositories
        run:  |
          dpkg --add-architecture arm64
          apt update
          
      - name: Install dependencies for cross-build
        run: apt install -y --allow-downgrades libarchive-tools curl devscripts equivs crossbuild-essential-arm64

      - name: Install dependencies for package build
        run: |
          mk-build-deps --host-arch arm64 --install --tool='apt-get -o Debug::pkgProblemResolver=yes --no-install-recommends --yes' debian/control
          rm adaptation-xiaomi-marble*.deb

      - name: Download latest kernel modules
        run: |
          mkdir -p /tmp/modules
          curl -L "https://github.com/droidian-marble/linux-droidian-marble-modules/releases/download/latest-modules/melt-modules.zip" | bsdtar -xvf- -C /tmp/modules
          mkdir -p usr/lib/adaptation-xiaomi-marble/modules/
          mv /tmp/modules/vendor_dlkm_modules/*.ko usr/lib/adaptation-xiaomi-marble/modules/
          
      - name: Build package
        run: |
          dpkg-buildpackage -us -uc -b --host-arch arm64
          
      - name: Move packages to out directory
        run: |
          mkdir /out
          cp ../*.deb /out/
          ls /out
          
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: adaptation-xiaomi-marble
          path: /out/*.deb
          if-no-files-found: error
          retention-days: 1

  prepare:
    runs-on: ubuntu-latest
    name: Create GitHub release
    needs: build

    steps:
      - name: Delete old latest release
        uses: dev-drprasad/delete-tag-and-release@v1.1
        with:
          delete_release: true # default: false
          tag_name: latest # tag name to delete
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag latest
        uses: tvdias/github-tagger@v0.0.1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          tag: latest

  publish:
    runs-on: ubuntu-latest
    needs: prepare

    name: Publish linux-image

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: out

      - name: Create latest release
        uses: softprops/action-gh-release@v2
        with:
          files: out/adaptation-xiaomi-marble/*.*
          tag_name: latest
          draft: false
          prerelease: false
